- hosts: all
  vars:
    packages:
      - docker.io
      - easystroke
      - gimp
      - gksu
      - gpointing-device-settings
      - nautilus
      - python-pip
      - unity-2d
      - account-plugin-*
      - android-tools-adb
      - apmd
      - apt-show-versions
      - battery-stats
      - build-essential
      - chromium-browser
      - cifs-utils
      - conky-all
      - emacs
      - emacs-goodies-el
      - ess
      - evince
      - evolution-data-server
      - evolution-data-server-common
      - feh
      - firefox
      - gimp
      - shotwell
      - gamt
      - gconf-editor
      - gfortran
      - git
      - gnome-panel
      - gparted
      - guile-1.8
      - icedtea-6-jre*
      - icedtea-7-jre-*
      - inotify-tools
      - ipython
      - jmol
      - kdirstat
      - krdc
      - laptop-mode-tools
      - lftp
      - lib32gfortran3
      - lib32stdc++6
      - libatlas3gf-base
      - libevent-dev
      - libgtk-3-0
      - libgtk-3-dev
      - libjava-gnome-jni
      - libjpeg62
      - libopenblas*
      - libpq-dev
      - libqt4-dev
      - libsdl1.2-dev
      - libx264-dev
      - libxml2-dev
      - libxpm-dev
      - libxslt1-dev
      - localepurge
      - markdown
      - openjdk-6-jre
      - openjdk-7-jre
      - pacpl
      - pandoc
      - pep8
      - powermanagement-interface
      - pyflakes
      - pylint
      - pymacs
      - pypy
      - python-dev
      - python-virtualenv
      - racket
      - r-base
      - suckless-tools
      - texlive
      - tmux
      - trayer
      - vim
      - virtualenvwrapper
      - vlc
      - winff
      - xbacklight
      - xbattbar
      - xclip
      - xmobar
      - xmonad
      - xrdp
      - xscreensaver*
         
    tasks:
      - include: tasks/ubuntu.yml
